// <auto-generated />
using System;
using DomainDrivenLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomainDrivenLibrary.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211083336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainDrivenLibrary.Books.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BorrowedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("borrowed_on");

                    b.Property<string>("BorrowerId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("borrowed_by");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("BorrowerId")
                        .HasDatabaseName("ix_books_borrowed_by");

                    b.HasIndex("Isbn")
                        .HasDatabaseName("ix_books_isbn");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("DomainDrivenLibrary.Borrowers.Borrower", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_borrowers");

                    b.ToTable("borrowers", (string)null);
                });

            modelBuilder.Entity("DomainDrivenLibrary.CatalogEntries.CatalogEntry", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Isbn")
                        .HasName("pk_catalog_entries");

                    b.ToTable("catalog_entries", (string)null);
                });

            modelBuilder.Entity("DomainDrivenLibrary.Books.Book", b =>
                {
                    b.HasOne("DomainDrivenLibrary.Borrowers.Borrower", null)
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_books_borrowers_borrowed_by");

                    b.HasOne("DomainDrivenLibrary.CatalogEntries.CatalogEntry", null)
                        .WithMany()
                        .HasForeignKey("Isbn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_books_catalog_entries_isbn");
                });
#pragma warning restore 612, 618
        }
    }
}
